name: Spotbugs

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Spotbugs
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn spotbugs:check -q
