name: Test

on: [pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn test -Dmaven.install.skip=true -Dcheckstyle.skip -Dspotbugs.skip -q
